"""initial schema

Revision ID: f0bd3a08dafd
Revises: 
Create Date: 2026-07-04 12:03:31.082092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0bd3a08dafd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'dispatcher', 'captain_viewer', name='adminrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('center_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('center_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas'))
    )
    op.create_table('retention_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_log'))
    )
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('blacklist_reason', sa.String(), nullable=True),
    sa.Column('fake_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_riders'))
    )
    op.create_index(op.f('ix_riders_phone'), 'riders', ['phone'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('fk_audit_log_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('blacklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('rider', 'driver', 'phone', name='blacklistentitytype'), nullable=False),
    sa.Column('entity_ref', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], name=op.f('fk_blacklist_entries_created_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklist_entries'))
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('license_doc_url', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', 'suspended', name='verificationstatus'), nullable=False),
    sa.Column('standing_tier', sa.Enum('new', 'standard', 'gold', name='standingtier'), nullable=False),
    sa.Column('credit_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_drivers_area_id_areas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers'))
    )
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=True)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('template_text', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.id'], name=op.f('fk_message_templates_updated_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_templates'))
    )
    op.create_index(op.f('ix_message_templates_key'), 'message_templates', ['key'], unique=True)
    op.create_table('pricing_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.Enum('int', 'decimal', 'bool', 'string', name='pricingvaluetype'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.id'], name=op.f('fk_pricing_config_updated_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_config'))
    )
    op.create_index(op.f('ix_pricing_config_key'), 'pricing_config', ['key'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('pickup_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_address_text', sa.String(), nullable=True),
    sa.Column('destination_text', sa.String(), nullable=True),
    sa.Column('ride_type', sa.Enum('ride', 'delivery', name='ridetype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'posted', 'claimed', 'confirmed', 'completed', 'no_show', 'cancelled', 'fake_flagged', 'unassigned', 'pending_review', name='bookingstatus'), nullable=False),
    sa.Column('assigned_driver_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rebook_of_booking_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_bookings_area_id_areas')),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.id'], name=op.f('fk_bookings_assigned_driver_id_drivers')),
    sa.ForeignKeyConstraint(['rebook_of_booking_id'], ['bookings.id'], name=op.f('fk_bookings_rebook_of_booking_id_bookings')),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_bookings_rider_id_riders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('captains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('revenue_share_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_captains_area_id_areas')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_captains_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_captains')),
    sa.UniqueConstraint('area_id', name=op.f('uq_captains_area_id'))
    )
    op.create_table('credit_topup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('amount_credits', sa.Integer(), nullable=False),
    sa.Column('amount_gmd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('wave', 'afrimoney', 'qmoney', 'cash', name='paymentmethod'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='topupstatus'), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_credit_topup_requests_driver_id_drivers')),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.id'], name=op.f('fk_credit_topup_requests_reviewed_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_topup_requests'))
    )
    op.create_index(op.f('ix_credit_topup_requests_status'), 'credit_topup_requests', ['status'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'free_trial', name='membershipstatus'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_memberships_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships'))
    )
    op.create_index(op.f('ix_memberships_driver_id'), 'memberships', ['driver_id'], unique=False)
    op.create_table('claim_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_driver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_claim_links_booking_id_bookings')),
    sa.ForeignKeyConstraint(['used_by_driver_id'], ['drivers.id'], name=op.f('fk_claim_links_used_by_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_links')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_claim_links_booking_id'))
    )
    op.create_index(op.f('ix_claim_links_token'), 'claim_links', ['token'], unique=True)
    op.create_table('consent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(), server_default='data_sharing', nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_consent_logs_booking_id_bookings')),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_consent_logs_rider_id_riders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_logs'))
    )
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'burn', 'refund', 'bonus', name='credittxntype'), nullable=False),
    sa.Column('amount_credits', sa.Integer(), nullable=False),
    sa.Column('amount_gmd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Enum('wave', 'afrimoney', 'qmoney', 'cash', name='paymentmethod'), nullable=True),
    sa.Column('approved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('topup_request_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['admin_users.id'], name=op.f('fk_credit_ledger_approved_by_admin_id_admin_users')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_credit_ledger_booking_id_bookings')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_credit_ledger_driver_id_drivers')),
    sa.ForeignKeyConstraint(['topup_request_id'], ['credit_topup_requests.id'], name=op.f('fk_credit_ledger_topup_request_id_credit_topup_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger'))
    )
    op.create_index(op.f('ix_credit_ledger_driver_id'), 'credit_ledger', ['driver_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('raised_by', sa.Enum('rider', 'driver', 'admin', name='disputeraisedby'), nullable=False),
    sa.Column('type', sa.Enum('no_show', 'fraud', 'safety', 'payment', name='disputetype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', name='disputestatus'), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_disputes_booking_id_bookings')),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['admin_users.id'], name=op.f('fk_disputes_resolved_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_otp_verifications_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_verifications'))
    )
    op.create_index(op.f('ix_otp_verifications_phone'), 'otp_verifications', ['phone'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating_value BETWEEN 1 AND 5', name=op.f('ck_ratings_rating_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_ratings_booking_id_bookings')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_ratings_driver_id_drivers')),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_ratings_rider_id_riders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_index(op.f('ix_otp_verifications_phone'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_credit_ledger_driver_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_table('consent_logs')
    op.drop_index(op.f('ix_claim_links_token'), table_name='claim_links')
    op.drop_table('claim_links')
    op.drop_index(op.f('ix_memberships_driver_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_credit_topup_requests_status'), table_name='credit_topup_requests')
    op.drop_table('credit_topup_requests')
    op.drop_table('captains')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_pricing_config_key'), table_name='pricing_config')
    op.drop_table('pricing_config')
    op.drop_index(op.f('ix_message_templates_key'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('blacklist_entries')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_riders_phone'), table_name='riders')
    op.drop_table('riders')
    op.drop_table('retention_log')
    op.drop_table('areas')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###

    # Alembic does not auto-drop inline Enum types on downgrade; drop them
    # explicitly so a subsequent upgrade does not fail with "type already exists".
    for enum_name in (
        "adminrole",
        "blacklistentitytype",
        "verificationstatus",
        "standingtier",
        "ridetype",
        "bookingstatus",
        "paymentmethod",
        "topupstatus",
        "membershipstatus",
        "credittxntype",
        "disputeraisedby",
        "disputetype",
        "disputestatus",
        "pricingvaluetype",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
